# /CyberStorm/docker-compose.yml

version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: cyberstorm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'cyberstorm_db'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: